// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvcPe6pSmTavc59slSXaZLZJO8y-09pOI',
    appId: '1:435734744714:web:f8f9bf51dd33dcf3b66773',
    messagingSenderId: '435734744714',
    projectId: 'reminder-7d022',
    authDomain: 'reminder-7d022.firebaseapp.com',
    storageBucket: 'reminder-7d022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqj0CZX-g7ec2FL5n9FF7LGRsLtwmgcUA',
    appId: '1:435734744714:android:92f822d1285091a8b66773',
    messagingSenderId: '435734744714',
    projectId: 'reminder-7d022',
    storageBucket: 'reminder-7d022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8LaHCt0tx67IYXzeNs3bCJllnw3x7rIE',
    appId: '1:435734744714:ios:6a238b616f1877e4b66773',
    messagingSenderId: '435734744714',
    projectId: 'reminder-7d022',
    storageBucket: 'reminder-7d022.appspot.com',
    iosBundleId: 'com.example.reminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8LaHCt0tx67IYXzeNs3bCJllnw3x7rIE',
    appId: '1:435734744714:ios:6a238b616f1877e4b66773',
    messagingSenderId: '435734744714',
    projectId: 'reminder-7d022',
    storageBucket: 'reminder-7d022.appspot.com',
    iosBundleId: 'com.example.reminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvcPe6pSmTavc59slSXaZLZJO8y-09pOI',
    appId: '1:435734744714:web:ff76060da7f2b126b66773',
    messagingSenderId: '435734744714',
    projectId: 'reminder-7d022',
    authDomain: 'reminder-7d022.firebaseapp.com',
    storageBucket: 'reminder-7d022.appspot.com',
  );

}